In [46]:
import re
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [47]:
raw_mail_data = pd.read_csv('mail_data.csv')

In [48]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
# replace the null values with a null string
# pd.notnull(raw_mail_data) -> Checks each value in dataset -> True  → value exists -> False → value is missing (NaN)
# .where(condition, value_if_false) -> If condition is True → keep original value -> If condition is False → replace with ''
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)), '')

In [50]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [51]:
mail_data.shape

(5572, 2)

In [52]:
# finding the count of different category
mail_data['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [53]:
# load the Label Encoder function
label_encoder = LabelEncoder()

In [54]:
labels = label_encoder.fit_transform(mail_data.Category)

In [55]:
mail_data['Target'] = labels

In [56]:
mail_data.head()

  Category                                            Message  Target
0      ham  Go until jurong point, crazy.. Available only ...       0
1      ham                      Ok lar... Joking wif u oni...       0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3      ham  U dun say so early hor... U c already then say...       0
4      ham  Nah I don't think he goes to usf, he lives aro...       0

spam - 1

ham - 0

In [57]:
X = mail_data['Message']
Y = mail_data['Target']

In [58]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [59]:
print(Y)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Target, Length: 5572, dtype: int64

In [60]:
import nltk
nltk.download("english")

[nltk_data] Error loading english: Package 'english' not found in
[nltk_data]     index

False

In [61]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [62]:
port_stem = PorterStemmer()

In [63]:
def stemming(content: str):
    stem_content  = re.sub('[^a-zA-Z]', ' ', content)
    stem_content = stem_content.lower()
    stem_content = stem_content.split()
    stem_content = [port_stem.stem(word) for word in stem_content if not word in stopwords.words('english')]
    stem_content = " ".join(stem_content)
    return stem_content

In [64]:
mail_data['Message'] = mail_data['Message'].apply(stemming)

In [65]:
X = mail_data['Message']

In [66]:
print(X)

0       go jurong point crazi avail bugi n great world...
1                                   ok lar joke wif u oni
2       free entri wkli comp win fa cup final tkt st m...
3                     u dun say earli hor u c alreadi say
4                    nah think goe usf live around though
                              ...
5567    nd time tri contact u u pound prize claim easi...
5568                                b go esplanad fr home
5569                                    piti mood suggest
5570    guy bitch act like interest buy someth els nex...
5571                                       rofl true name
Name: Message, Length: 5572, dtype: object

In [67]:
# Splitting the data into training data & test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 3)
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(5572,)
(4457,)
(1115,)

In [68]:
# transform the text data to feature vectors that can be used as input to the Logistic regression
feature_extraction = TfidfVectorizer()

X_train_features = feature_extraction.fit_transform(X_train)
X_test_featrures = feature_extraction.transform(X_test)

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [69]:
print(X_train)

3075                                      know msg recent
1787    know god creat gap finger one made come amp fi...
1614                                 thnx dude u guy nite
4304                                             yup free
3266    want new nokia colour phone deliveredtomorrow ...
                              ...
789     free top polyphon tone call nation rate get to...
968     u want come back beauti necklac token heart th...
1667           guess spent last night phase fourth dimens
3321    eh sorri leh din c ur msg sad alreadi lar watc...
1688    free top rington sub weekli rington get st wee...
Name: Message, Length: 4457, dtype: object

In [70]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36052 stored elements and shape (4457, 5622)>
  Coords	Values
  (0, 2600)	0.4325392837057532
  (0, 3114)	0.5073237155975543
  (0, 3928)	0.745340469613455
  (1, 2600)	0.15683774727819497
  (1, 1943)	0.2256004398050583
  (1, 1043)	0.3006799879436135
  (1, 1862)	0.601359975887227
  (1, 1696)	0.29364542876489014
  (1, 3380)	0.1707587531492112
  (1, 2861)	0.245309755278111
  (1, 929)	0.15415105276919708
  (1, 167)	0.20816138236838674
  (1, 1685)	0.278001264969614
  (1, 2182)	0.24719223864006132
  (1, 2071)	0.25346274799352675
  (1, 2803)	0.16484914990688035
  (2, 4893)	0.6365475059225226
  (2, 1376)	0.47200468292779757
  (2, 2043)	0.4027623053879194
  (2, 3257)	0.45804080315693874
  (3, 5607)	0.8114386733953441
  (3, 1790)	0.5844375752109064
  (4, 1790)	0.5505632401771141
  (4, 5306)	0.18471344682862334
  (4, 3225)	0.20767369214736922
  :	:
  (4455, 2688)	0.2988978141358583
  (4455, 5319)	0.2599149133596718
  (4455, 5167)	0.18759696806228005
  (4455, 3346)	0.2934198065705985
  (4455, 2648)	0.29700198906044567
  (4455, 145)	0.24912874691887366
  (4455, 4478)	0.2207167011215539
  (4455, 5068)	0.28403482065051106
  (4455, 4596)	0.22188151274446055
  (4455, 4096)	0.3204701470174546
  (4455, 1438)	0.3343759341093223
  (4455, 1249)	0.3539750402283813
  (4456, 1790)	0.3311917011047664
  (4456, 4206)	0.16914667747042617
  (4456, 1900)	0.14186267058098184
  (4456, 4551)	0.22214410074587662
  (4456, 4649)	0.2714381411025111
  (4456, 4605)	0.18387395221003588
  (4456, 5350)	0.37701544124260017
  (4456, 5353)	0.2543367431239565
  (4456, 4398)	0.22127157303669834
  (4456, 4035)	0.46654328766719216
  (4456, 4993)	0.2470988667218805
  (4456, 4652)	0.31822887355468726
  (4456, 3548)	0.22127157303669834

In [71]:
# Logistic Regression
model = LogisticRegression()

In [73]:
# training the Logistic Regression model with the training data
model.fit(X_train_features, Y_train)

LogisticRegression()

In [74]:
prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(prediction_on_training_data, Y_train)

In [75]:
print('Accuracy on training data : ', accuracy_on_training_data)

Accuracy on training data :  0.9710567646398923

In [76]:
prediction_on_test_data = model.predict(X_test_featrures)
accuracy_on_testing_data = accuracy_score(prediction_on_test_data, Y_test)

In [77]:
print('Accuracy on testing data : ', accuracy_on_testing_data)

Accuracy on testing data :  0.967713004484305

In [79]:
input_mail = ["I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times"]

# 1. Apply SAME preprocessing (stemming)
input_data = [stemming(mail) for mail in input_mail]

# 2. Convert text → numerical features using SAME vectorizer
input_data_feature = feature_extraction.transform(input_data)

# making prediction
prediction = model.predict(input_data_feature)
print(prediction)

if (prediction[0]==0):
    print('Ham mail')
else:
    print("Spam Mail")

[0]
Ham mail