In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [23]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [24]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1)

In [25]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [26]:
onehot_encoder_geo = OneHotEncoder()
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [27]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [28]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# random_state ensures that the train-test split is always the same every time you run the code.

In [31]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression, when we do not apply any activation function its by default is linear activation function
])

# compile the model
# in regression we use mean_absolute_error or mean_squared_error
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

2025-11-24 18:01:13.333717: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-11-24 18:01:13.334028: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-11-24 18:01:13.334042: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2025-11-24 18:01:13.334441: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-11-24 18:01:13.334745: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [41]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [42]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [43]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

2025-11-24 19:00:06.437228: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

250/250 [==============================] - 2s 4ms/step - loss: 100424.0469 - mae: 100424.0469 - val_loss: 98697.8672 - val_mae: 98697.8672
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 100314.7266 - mae: 100314.7266 - val_loss: 98450.1562 - val_mae: 98450.1562
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 99865.9062 - mae: 99865.9062 - val_loss: 97735.7266 - val_mae: 97735.7266
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 98921.6562 - mae: 98921.6562 - val_loss: 96511.6484 - val_mae: 96511.6484
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 97496.0625 - mae: 97496.0625 - val_loss: 94880.3594 - val_mae: 94880.3594
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 95661.7109 - mae: 95661.7109 - val_loss: 93025.2188 - val_mae: 93025.2188
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 93709.1172 - mae: 93709.1172 - val_loss: 91270.0391 - val_mae: 91270.0391
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 91924.3438 - mae: 91924.3438 - val_loss: 89719.6094 - val_mae: 89719.6094
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 90475.9141 - mae: 90475.9141 - val_loss: 88431.8281 - val_mae: 88431.8281
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 89306.5625 - mae: 89306.5625 - val_loss: 87381.7578 - val_mae: 87381.7578
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 88311.0156 - mae: 88311.0156 - val_loss: 86504.8516 - val_mae: 86504.8516
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 87505.4297 - mae: 87505.4297 - val_loss: 85691.1719 - val_mae: 85691.1719
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 86792.2266 - mae: 86792.2266 - val_loss: 84978.1562 - val_mae: 84978.1562
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 86076.6094 - mae: 86076.6094 - val_loss: 84214.3281 - val_mae: 84214.3281
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 85344.7734 - mae: 85344.7734 - val_loss: 83469.7734 - val_mae: 83469.7734
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 84560.5547 - mae: 84560.5547 - val_loss: 82698.7344 - val_mae: 82698.7344
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 83810.7422 - mae: 83810.7422 - val_loss: 81895.6562 - val_mae: 81895.6562
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 82975.4453 - mae: 82975.4453 - val_loss: 81053.7500 - val_mae: 81053.7500
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 82145.2109 - mae: 82145.2109 - val_loss: 80219.2266 - val_mae: 80219.2266
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 81254.8516 - mae: 81254.8516 - val_loss: 79365.9453 - val_mae: 79365.9453
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 80412.0078 - mae: 80412.0078 - val_loss: 78601.9453 - val_mae: 78601.9453
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 79567.9609 - mae: 79567.9609 - val_loss: 77780.8594 - val_mae: 77780.8594
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 78667.2500 - mae: 78667.2500 - val_loss: 76963.1094 - val_mae: 76963.1094
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 77764.0156 - mae: 77764.0156 - val_loss: 76049.4922 - val_mae: 76049.4922
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 76819.9062 - mae: 76819.9062 - val_loss: 75190.8594 - val_mae: 75190.8594
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 75892.4688 - mae: 75892.4688 - val_loss: 74325.8672 - val_mae: 74325.8672
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 74984.6250 - mae: 74984.6250 - val_loss: 73451.3125 - val_mae: 73451.3125
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 74050.1484 - mae: 74050.1484 - val_loss: 72505.6406 - val_mae: 72505.6406
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 73011.9688 - mae: 73011.9688 - val_loss: 71485.3203 - val_mae: 71485.3203
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 71941.0859 - mae: 71941.0859 - val_loss: 70472.1797 - val_mae: 70472.1797
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 70824.2891 - mae: 70824.2891 - val_loss: 69310.3828 - val_mae: 69310.3828
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 69477.5703 - mae: 69477.5703 - val_loss: 67840.5391 - val_mae: 67840.5391
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 67825.1797 - mae: 67825.1797 - val_loss: 66067.4297 - val_mae: 66067.4297
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 65921.7891 - mae: 65921.7891 - val_loss: 64081.3516 - val_mae: 64081.3516
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 63910.4062 - mae: 63910.4062 - val_loss: 62033.8164 - val_mae: 62033.8164
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 61833.8320 - mae: 61833.8320 - val_loss: 60059.3398 - val_mae: 60059.3398
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 59890.8750 - mae: 59890.8750 - val_loss: 58284.5547 - val_mae: 58284.5547
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 58148.6328 - mae: 58148.6328 - val_loss: 56747.9805 - val_mae: 56747.9805
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 56619.6523 - mae: 56619.6523 - val_loss: 55477.6484 - val_mae: 55477.6484
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 55329.1289 - mae: 55329.1289 - val_loss: 54438.8281 - val_mae: 54438.8281
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 54266.2227 - mae: 54266.2227 - val_loss: 53583.9102 - val_mae: 53583.9102
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 53370.3477 - mae: 53370.3477 - val_loss: 52873.6094 - val_mae: 52873.6094
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 52640.2305 - mae: 52640.2305 - val_loss: 52323.8906 - val_mae: 52323.8906
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 52043.5977 - mae: 52043.5977 - val_loss: 51862.8984 - val_mae: 51862.8984
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 51546.4766 - mae: 51546.4766 - val_loss: 51501.2773 - val_mae: 51501.2773
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 51143.7695 - mae: 51143.7695 - val_loss: 51186.0781 - val_mae: 51186.0781
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 50815.4883 - mae: 50815.4883 - val_loss: 50927.3945 - val_mae: 50927.3945
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 50541.6797 - mae: 50541.6797 - val_loss: 50705.6445 - val_mae: 50705.6445
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 50322.5195 - mae: 50322.5195 - val_loss: 50536.0742 - val_mae: 50536.0742
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 50151.5156 - mae: 50151.5156 - val_loss: 50399.8320 - val_mae: 50399.8320
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 50021.8203 - mae: 50021.8203 - val_loss: 50300.1562 - val_mae: 50300.1562
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49926.5859 - mae: 49926.5859 - val_loss: 50224.2695 - val_mae: 50224.2695
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49851.7266 - mae: 49851.7266 - val_loss: 50156.3359 - val_mae: 50156.3359
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49789.1250 - mae: 49789.1250 - val_loss: 50116.5195 - val_mae: 50116.5195
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49741.0898 - mae: 49741.0898 - val_loss: 50075.7070 - val_mae: 50075.7070
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49700.4492 - mae: 49700.4492 - val_loss: 50051.0391 - val_mae: 50051.0391
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49675.6836 - mae: 49675.6836 - val_loss: 50029.3828 - val_mae: 50029.3828
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49645.8711 - mae: 49645.8711 - val_loss: 50013.7227 - val_mae: 50013.7227
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49625.3438 - mae: 49625.3438 - val_loss: 50008.7539 - val_mae: 50008.7539
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49608.1992 - mae: 49608.1992 - val_loss: 50002.0508 - val_mae: 50002.0508
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49598.3164 - mae: 49598.3164 - val_loss: 49998.0039 - val_mae: 49998.0039
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49589.0039 - mae: 49589.0039 - val_loss: 49992.4531 - val_mae: 49992.4531
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49584.3516 - mae: 49584.3516 - val_loss: 49991.0352 - val_mae: 49991.0352
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.7461 - mae: 49577.7461 - val_loss: 49989.2344 - val_mae: 49989.2344
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49574.7812 - mae: 49574.7812 - val_loss: 49980.3164 - val_mae: 49980.3164
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 49573.0938 - mae: 49573.0938 - val_loss: 49987.3359 - val_mae: 49987.3359
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49569.9297 - mae: 49569.9297 - val_loss: 49982.3320 - val_mae: 49982.3320
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 49570.0000 - mae: 49570.0000 - val_loss: 49981.1562 - val_mae: 49981.1562
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 49567.7891 - mae: 49567.7891 - val_loss: 49983.0977 - val_mae: 49983.0977
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 49567.2148 - mae: 49567.2148 - val_loss: 49978.3281 - val_mae: 49978.3281
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 49564.0898 - mae: 49564.0898 - val_loss: 49966.3008 - val_mae: 49966.3008
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 49563.6992 - mae: 49563.6992 - val_loss: 49968.7734 - val_mae: 49968.7734
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.2070 - mae: 49562.2070 - val_loss: 49976.1055 - val_mae: 49976.1055
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 49563.7266 - mae: 49563.7266 - val_loss: 49977.0742 - val_mae: 49977.0742
Epoch 75/100
250/250 [==============================] - 1s 4ms/step - loss: 49562.3008 - mae: 49562.3008 - val_loss: 49969.0000 - val_mae: 49969.0000
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.4492 - mae: 49562.4492 - val_loss: 49956.1133 - val_mae: 49956.1133
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.6914 - mae: 49562.6914 - val_loss: 49961.3555 - val_mae: 49961.3555
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 49563.2227 - mae: 49563.2227 - val_loss: 49968.4023 - val_mae: 49968.4023
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 49561.5977 - mae: 49561.5977 - val_loss: 49970.1875 - val_mae: 49970.1875
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.3125 - mae: 49562.3125 - val_loss: 49968.1953 - val_mae: 49968.1953
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 49561.5195 - mae: 49561.5195 - val_loss: 49960.4219 - val_mae: 49960.4219
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.3789 - mae: 49562.3789 - val_loss: 49962.3984 - val_mae: 49962.3984
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 49561.2109 - mae: 49561.2109 - val_loss: 49966.3906 - val_mae: 49966.3906
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 49562.3203 - mae: 49562.3203 - val_loss: 49967.3008 - val_mae: 49967.3008
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 49564.2344 - mae: 49564.2344 - val_loss: 49974.2773 - val_mae: 49974.2773
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 49560.9688 - mae: 49560.9688 - val_loss: 49970.3906 - val_mae: 49970.3906

In [44]:
%load_ext tensorboard

In [46]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 47292), started 0:04:00 ago. (Use '!kill 47292' to kill it.)

In [47]:
## Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE : {test_mae}")

63/63 [==============================] - 0s 3ms/step - loss: 49956.1133 - mae: 49956.1133
Test MAE : 49956.11328125

In [48]:
model.save('regression_model.h5')

/opt/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(